### ISSUE TITLE
Authentication with SQL / JWT

### ISSUE THREAD

**Issue by sammiefrog** [sammiefrog/CalendarApp#9]
- [x] Create User Model with associations

- [x] add passport middleware 

- [x]  start routes for auth and controllers on back end

- [ ] connect to front end login/registration components
